<?php

namespace SiteWebBundle\Repository;

/**
 * vendeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class vendeurRepository extends \Doctrine\ORM\EntityRepository
{
}
